-- Seed data for local development
-- This file is automatically executed on postgres container init
-- NOTE: The broker creates its own tables (users, sessions, saves, etc.) on startup.
-- Only add seed data here that doesn't conflict with the broker's schema.
