-- Seed data for local development
-- The broker creates all tables on startup via init_db().
-- This file only inserts sample data AFTER the broker has run once.
--
-- To use: after the broker has started and created tables, run:
--   docker compose exec postgres psql -U claudetorio -d claudetorio -f /docker-entrypoint-initdb.d/seed.sql
--
-- Or just let the broker create empty tables (recommended for clean dev).
