services:
  caddy:
    profiles: ["disabled"]

  broker:
    ports:
      - "8080:8080"
    environment:
      - FACTORIO_CLIENT_VOLUME=claudetorio_factorio_client

  frontend:
    ports:
      - "3000:3000"
